//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalestraTest.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casi_disattivazione_abbonamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Casi_disattivazione_abbonamento()
        {
            this.RapportoClienti = new HashSet<RapportoCliente>();
        }
    
        public int id { get; set; }
        public string motivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RapportoCliente> RapportoClienti { get; set; }
    }
}
