//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalestraTest.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrezziAbbonamenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PrezziAbbonamenti()
        {
            this.RapportoClienti = new HashSet<RapportoCliente>();
        }
    
        public int id { get; set; }
        public string titolo { get; set; }
        public Nullable<decimal> prezzo { get; set; }
        public bool is_periodico { get; set; }
        public Nullable<int> validita_giorni { get; set; }
        public Nullable<int> validita_mesi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RapportoCliente> RapportoClienti { get; set; }
    }
}
