//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalestraTest.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class RapportoCliente
    {
        public string ID_Tessera { get; set; }
        public Nullable<System.DateTime> Data_Iscrizione { get; set; }
        public Nullable<System.DateTime> Data_Pagamento { get; set; }
        public Nullable<System.DateTime> Data_Scadenza { get; set; }
        public Nullable<System.DateTime> Data_Certificato { get; set; }
        public Nullable<System.DateTime> Data_Scadenza_Certificato { get; set; }
        public string Note { get; set; }
        public bool Abilitato { get; set; }
        public Nullable<int> Tipo_Iscrizione { get; set; }
        public string Extra { get; set; }
        public Nullable<int> N_EntrateRimanenti { get; set; }
        public Nullable<System.DateTime> Data_Annuale { get; set; }
        public Nullable<System.DateTime> Data_AnnualeScadenza { get; set; }
        public Nullable<System.DateTime> Data_Disattivazione { get; set; }
        public Nullable<int> Codice_disattivazione { get; set; }
    
        public virtual Casi_disattivazione_abbonamento Casi_disattivazione_abbonamento { get; set; }
        public virtual PrezziAbbonamenti PrezziAbbonamenti { get; set; }
        public virtual Utente Utenti { get; set; }
    }
}
