//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalestraTest.App_Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UtentiPalestraEntities : DbContext
    {
        public UtentiPalestraEntities()
            : base("name=UtentiPalestraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Casi_disattivazione_abbonamento> Casi_disattivazione_abbonamento { get; set; }
        public virtual DbSet<PrezziAbbonamenti> PrezziAbbonamenti { get; set; }
        public virtual DbSet<RapportoCliente> RapportoClienti { get; set; }
        public virtual DbSet<Utente> Utenti { get; set; }
    }
}
