//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PalestraTest.App_Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utente
    {
        public string ID_Tessera { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public string Indirizzo { get; set; }
        public string Citta { get; set; }
        public string Provincia { get; set; }
        public string Telefono { get; set; }
        public string Pubblicita { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public bool FesteggiaCompleanno { get; set; }
    
        public virtual RapportoCliente RapportoClienti { get; set; }
    }
}
